version: "1.0"
info:
  model: int-scaffold
packages:
- name: Dada1Project
  gitServerName: sumitaShared
  gitUrl: https://github.com/sumitaPriyadarshy
  gitUsername: sumitaPriyadarshy
  gitBranch: main
services:
- serviceName: project.dada1.integrations:test1
  packages:
  - name: Dada1Project
    version: "1.0"
